server:
  port: 8989
spring:
  application:
    name: eurekaClient
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    # 指定服务中心注册地址
    service-url:
      defaultZone: http://localhost:8761/eureka
