# eureka server 端口号默认为8761
server:
  port: 8761
# eureka server服务中心注册地址 暴漏服务地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    # 关闭eureka client立即注册
    fetch-registry: false
    # 让当前应用仅仅是服务注册中心
    register-with-eureka: false
# 指定服务名称
spring:
  application:
    name: eurekaServer
